sudo: required

language: node_js

cache:
    directories:
      - node_modules

node_js:
  - "8"

script:
  - echo "npm test temporarily disabled"

install:
  - npm install
  - source .travis/parse_tag.sh
  - bash .travis/build_swap.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: kyber-swap
    region: ap-southeast-1
    acl: public_read
    local_dir: dist/$SWAP_ENV
    upload_dir: $TRAVIS_COMMIT/$SWAP_ENV
    skip_cleanup: true
    on:
      all_branches: true
      tag: true
      condition: $TRAVIS_TAG =~ ^deploy.*$
